### ISSUE TITLE
install instructions?

### ISSUE THREAD

**Issue by toprak** [EnergoStalin/subtitle-translate-mpv#1]

**Comment by EnergoStalin** [comment]
Just clone repository into mpv [scripts folder](https://mpv.io/manual/stable/#script-location) and make sure CrowTranslate available in path. For windows you can install it using [winget](https://winstall.app/apps/CrowTranslate.CrowTranslate). For config i already specified example in readme.

**Comment by toprak** [comment]
@EnergoStalin Thanks it worked but its too slow what can I do? I made delay 0 from config but did not do the trick

**Comment by EnergoStalin** [comment]
In general you need a negative initial delay so subtitles will appear earlier and script have time to translate. Then it will be automatically adjusted by [average](https://github.com/EnergoStalin/subtitle-translate-mpv/blob/master/modules/average.lua) crow translation time.

May become slightly inaccurate when running long time and you have unstable internet connection(guess i need to add detection for internet connection problems to automate this like don't allow delay go beyond some treshhold). But lua branch now is unmaintaned i did tried to rewrite it to js with normal async support in master-js branch but abandoned it at some point for the sake of alternatives like you know miru and language specific torrent trackers. To put it simply Lua works fine in stable environment but handles definitely not all edge cases.

So you need to:
- experimenting with negative delay to adjust timings by your base average crow response speed(I have -0.5 and it's enough for me. Means half a second earlier but actually crow responds around 200-300ms it's a good thing to set it a bit bigger and let average module adjust it after).

**Comment by EnergoStalin** [comment]
Added benchmark script for easier setup. Still need to put it into config file manually.

And hopefully fixed your issue because i somehow 🤦🏻‍♂️ measured time after calling crow but should done it before.

**Comment by EnergoStalin** [comment]
Yeah after i said what it's unmaintaned)

**Comment by toprak** [comment]
thank you so much @EnergoStalin now my pc got broken i will be able to check it on this saturday :)

**Comment by candrapersada** [comment]
`winget install --id CrowTranslate.CrowTranslate`
not found in winget

**Comment by EnergoStalin** [comment]
Did they get [rebranded](https://github.com/microsoft/winget-pkgs/issues/188219)? Seems like so try KDE.CrowTranslate. Will update readme asap.

Also why not [Console-Translate](https://github.com/Lifailon/Console-Translate) as far i can see it's better. Not using supported powershell version?
