### ISSUE TITLE
[Feature]: Only resizing translation's size

### ISSUE THREAD

**Issue by fideliochan** [EnergoStalin/subtitle-translate-mpv#10]
**Is your feature request related to a problem? Please describe.**
the size difference between primary and translation is very disproportionate and uncomfortable
**Describe the solution you'd like**
allow users to resize translation only

**Describe alternatives you've considered**
I did not

**Additional context**
Also on linux it doesn't read the subtitle-translate-mpv.conf file in the script-opts folder for some strange reason. I change the settings in main.lua.

**Comment by EnergoStalin** [comment]
> Also on linux it doesn't read the subtitle-translate-mpv.conf file

Cause it should be subtitle_translate_mpv.conf if script folder is subtitle-translate-mpv according to [mp.get_script_name()](https://mpv.io/manual/stable/#lua-scripting-mp-get-script-name()) which is stated in readme btw.
https://github.com/EnergoStalin/subtitle-translate-mpv/blob/cc1a1e558580d04c9be3e81303a686f4dbad62bc/README.md?plain=1#L35

**Comment by EnergoStalin** [comment]
> sometimes script can't see the styled text and does not translate it

-> New properly filled bug report with file and timestamp

> can you add more customization the second subtitle(translated one) like different color for each subtitle (original and translated)

I will add custom ass style option for original and translated lines that will wrap it into it later.

**Comment by EnergoStalin** [comment]
Any way I can obtain file with lines causes problems. Following with timestamp on which styles broke.
