### ISSUE TITLE
[Bug]: hieroglyphs are displayed in subtitles. windows 11  

### ISSUE THREAD

**Issue by may-uri** [EnergoStalin/subtitle-translate-mpv#12]
**Describe the bug**

instead of russian letters, hieroglyphs are displayed in subtitles

**Steps to reproduce**

problem is most likely related to my windows, but hopefully you know how to help

**Mpv version**
```
mpv 0.36.0 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Tue Aug 01 10:56:31 2023
libplacebo version: v6.292.0-78-gabf34ba-dirty
FFmpeg version: N-111661-g567e78b28
FFmpeg library versions:
   libavutil       58.14.100
   libavcodec      60.22.100
   libavformat     60.10.100
   libswscale      7.3.100
   libavfilter     9.10.100
   libswresample   4.11.100
```

**Script config**

everything is default from readme, only the font has been changed to Arial

**Full mpv log from errored session**
```
https://pastebin.com/3AxT4nJx
```
**Additional context**

visual representation of the problem:
![Screenshot 2024-06-08 234253](https://github.com/EnergoStalin/subtitle-translate-mpv/assets/120062742/7cdcf717-8462-41c6-84a7-cc39c3be217b)

Console-Translate in powershell:
![image](https://github.com/EnergoStalin/subtitle-translate-mpv/assets/120062742/72c59972-17fa-44bc-8b22-5d909603c139)

**Comment by EnergoStalin** [comment]
Check pwsh works in UTF8 mode.

```pwsh
[System.Text.Encoding]::Default.EncodingName
```

Should return something like this `Unicode (UTF-8)`
