### ISSUE TITLE
[subtitle_translate_mpv] table: 0x01ce542f4b78 Error

### ISSUE THREAD

**Issue by toprak** [EnergoStalin/subtitle-translate-mpv#5]
**Describe the bug**
Newly installed error
**To Reproduce**
>mpv .mp4 on cmd
[subtitle_translate_mpv] table: 0x01ce542f4b78
**Expected behavior**
Work

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser edge
 - Version 120
**Additional context**
If i dont disable this script, it does not show subtitles.

**Comment by EnergoStalin** [comment]
Ahh my bad din't customized bug report template. Cant do much with this information it works on sample [.mp4 file](https://file-examples.com/wp-content/storage/2017/04/file_example_MP4_480_1_5MG.mp4) for me. Please update to latest version and refill issue.

As far as i still remember some powershell single line update
```powershell
cd $env:APPDATA && cd Roaming/.mpv/scripts/subtitle-translate-mpv && git pull
```

**Comment by toprak** [comment]
it was already latest one, i will try again.

**Comment by EnergoStalin** [comment]
I added track list dumping in debug logs a couple minutes ago

**Comment by EnergoStalin** [comment]
Spoke too soon will fix asap

**Comment by EnergoStalin** [comment]
Double check if you have [crow](https://crow-translate.github.io/) in path.

**Comment by toprak** [comment]
@EnergoStalin Double checked and its in path, how can I find the debug log, i started mpv with -v but there is only [subtitle_translate_mpv] table: 0x02cab712b938 [subtitle_translate_mpv] table: 0x02cab7133fa8 [subtitle_translate_mpv] table: 0x02cab6ef70a0 them as error, how can i debug it

**Comment by EnergoStalin** [comment]
Can you call crow like this from console where you start mpv and get output?
```bash
crow -l en -t ru -b aboba
```

If it's work make sure you on latest version and send log like this(it wont do much more than -v tho cause i didn't commit error messages yet)
```bash
mpv --msg-level=subtitle_translate_mpv=trace file_caused_problems >& log.txt
```
Or without >& log.txt to have it in console. Not sure >& will work in windows tho.

**Comment by EnergoStalin** [comment]
You can update and send logs. Now it should be more clear

**Comment by toprak** [comment]
nevermind, i will use manual translating programs, thanks for helping though.

**Comment by toprak** [comment]
@EnergoStalin it works somehow lol

**Comment by EnergoStalin** [comment]
Sounds good. Honestly i searched something like this but didn't found something what i like back then. Definitely will add it when have time.
