### ISSUE TITLE
[Feature]: deepl-cli provider

### ISSUE THREAD

**Issue by EnergoStalin** [EnergoStalin/subtitle-translate-mpv#6]
**Is your feature request related to a problem? Please describe.**
Lack of translator options.

**Describe the solution you'd like**
Add [deepl-cli](https://github.com/eggplants/deepl-cli) as provider

**Describe alternatives you've considered**
tolerate

**Additional context**
none

**Comment by toprak** [comment]
https://github.com/Lifailon/Console-Translate

**Comment by EnergoStalin** [comment]
deepl cli is too slow 8s in worst case for request and 3s in best. So wont support. Console-Translate is pretty good tho except for case described [here](https://github.com/EnergoStalin/subtitle-translate-mpv#providers).

**Comment by EnergoStalin** [comment]
okay nevermind it's my issue just got too impatient. already fixed
