### ISSUE TITLE
[Bug]: Translation doesn't work if subtitles built-in MKV file.

### ISSUE THREAD

**Issue by rootBrz** [EnergoStalin/subtitle-translate-mpv#9]
**Describe the bug**

Translation doesn't work if subtitles in MKV file. When translation is enabled, subtitles completely disappears. If .srt file present, translation works.

**Mpv version**
```
mpv v0.37.0 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Mar 31 2024 10:04:09
libplacebo version: v6.338.2
FFmpeg version: n6.1.1
FFmpeg library versions:
   libavutil       58.29.100
   libavcodec      60.31.102
   libavformat     60.16.100
   libswscale      7.5.100
   libavfilter     9.12.100
   libswresample   4.12.100
```

**Comment by EnergoStalin** [comment]
First of all incomplete report. Second check if it's text subtitles stream ass or srt. Script wont translate if it's rendered subtitle stream(forgot how this format called).

**Comment by rootBrz** [comment]
Format is PGS, just read about it, probably it cannot be supported.

[log.txt](https://github.com/EnergoStalin/subtitle-translate-mpv/files/14856844/log.txt)

**Comment by EnergoStalin** [comment]
Yep then solved
